### ISSUE TITLE
difference with Huggingface implementation?

### ISSUE THREAD

**Issue by bakachan19** [Andron00e/CLIPForImageClassification#1]
Hi,
Thanks for this great work.
I was looking at the implementation of CLIPForImageClassification of this repo and comparing it with the from HuggingFace.
From my understanding, the HuggingFace implementation is based on this repository. If so, I was wondering why the HF implementation uses torch.mean(): https://github.com/huggingface/transformers/blob/09f9f566de83eef1f13ee83b5a1bbeebde5c80c1/src/transformers/models/clip/modeling_clip.py#L1377-L1382
```
        sequence_output = outputs[0]

        # average pool the patch tokens
        sequence_output = torch.mean(sequence_output[:, 1:, :], dim=1)
        # apply classifier
        logits = self.classifier(sequence_output)
```
while in this repository we have the linear layer applied on top of the image embeddings:
```
        logits = self.head(clip_outputs.image_embeds)
```

Thank you!

**Comment by Andron00e** [comment]
Thank you for paying attention to my work) 
Always nice to try for the sake of such comments!

Moreover, if you have any possible changes, feel free to mention them in order to help me in further improvements. 
CLIPForImageClassification can be implemented in several different ways, since it is a kind of linear probing of zero-shot classifier. Probing linear layer can be implemented directly after the ```.image_embeds``` or after the ```.logits_per_image```.  Guys from HuggingFace suggested to use the second variant, meanwhile I have mentioned both of them in [#27802](https://github.com/huggingface/transformers/issues/27802) pr.
 
Sincerely, Andron00e

**Comment by bakachan19** [comment]
Dear @Andron00e,
thank you for taking the time to reply. 

Oh, I see.
I would like to use CLIPForImageClassification for some fine-tuning. Is there any benefit of using the ```.logits_per_image``` approach instead of ```.image_embeds``` ? 

Have a great day!

**Comment by Andron00e** [comment]
In my opinion, the difference is not sufficiently large, using the ```.logits_per_image``` is less general, but, meanwhile is more natural for zero-shot models. In our paper I implemented linear probing of CLIP with ```.logits_per_image```, see https://github.com/Andron00e/SparseCBM/blob/main/experiments/linear_probing_clip.ipynb.

**Comment by bakachan19** [comment]
@Andron00e thanks for sharing the paper and the corresponding code. The material you shared is very useful and informative.
